services:
  mongodb:
    image: mongo:latest
    container_name: sentinel_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:alpine
    container_name: sentinel_redis
    ports:
      - "6379:6379"

  # Adding your Ingestion Server
  api-server:
    build: ./server
    container_name: sentinel_backend
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
      - redis

  # Adding your React Dashboard
  frontend:
    build: ./dashboard
    container_name: sentinel_frontend
    ports:
      - "5173:5173"

volumes:
  mongo_data: